const API_ENDPOINT = "https://yts.ag/api/v2";

module.exports = {
  COMMENT_ADD: `${API_ENDPOINT}/make_comment.json`,
  COMMENT_DELETE: `${API_ENDPOINT}/delete_comment.json`,
  COMMENT_LIKE: `${API_ENDPOINT}/like_comment.json`,
  COMMENT_REPORT: `${API_ENDPOINT}/report_comment.json`,
  LIKE_MOVIE: `${API_ENDPOINT}/like_movie.json`,
  LIST_UPCOMING: `${API_ENDPOINT}/list_upcoming.json`,
  LIST_MOVIES: `${API_ENDPOINT}/list_movies.json`,
  MOVIE_BOOKMARK_ADD: `${API_ENDPOINT}/add_movie_bookmark.json`,
  MOVIE_BOOKMARK_DELETE: `${API_ENDPOINT}/delete_movie_bookmark.json`,
  MOVIE_BOOKMARK_GET: `${API_ENDPOINT}/get_movie_bookmarks.json`,
  MOVIE_COMMENTS: `${API_ENDPOINT}/movie_comments.json`,
  MOVIE_DETAILS: `${API_ENDPOINT}/movie_details.json`,
  MOVIE_PARENTAL_GUIDES: `${API_ENDPOINT}/movie_parental_guides.json`,
  MOVIE_REVIEWS: `${API_ENDPOINT}/movie_reviews.json`,
  MOVIE_SUGGESTIONS: `${API_ENDPOINT}/movie_suggestions.json`,
  REQUEST_MAKE: `${API_ENDPOINT}/make_request.json`,
  USER_DETAILS: `${API_ENDPOINT}/user_details.json`,
  USER_FORGOT_PASSWORD: `${API_ENDPOINT}/user_forgot_password.json`,
  USER_KEY: `${API_ENDPOINT}/user_get_key.json`,
  USER_PROFILE: `${API_ENDPOINT}/user_profile.json`,
  USER_REGISTER: `${API_ENDPOINT}/user_register.json`,
  USER_RESET_PASSWORD: `${API_ENDPOINT}/user_reset_password.json`,
  USER_SETTINGS_EDIT: `${API_ENDPOINT}/user_edit_settings.json`,
};
