module.exports = {
  COMMENT_ADD: 'https://yts.ag/api/v2/make_comment.json',
  COMMENT_DELETE: 'https://yts.ag/api/v2/delete_comment.json',
  COMMENT_LIKE: 'https://yts.ag/api/v2/like_comment.json',
  COMMENT_REPORT: 'https://yts.ag/api/v2/report_comment.json',
  LIKE_MOVIE: 'https://yts.ag/api/v2/like_movie.json',
  LIST_UPCOMING: 'https://yts.ag/api/v2/list_upcoming.json',
  LIST_MOVIES: 'https://yts.ag/api/v2/list_movies.json',
  MOVIE_BOOKMARK_ADD: 'https://yts.ag/api/v2/add_movie_bookmark.json',
  MOVIE_BOOKMARK_DELETE: 'https://yts.ag/api/v2/delete_movie_bookmark.json',
  MOVIE_BOOKMARK_GET: 'https://yts.ag/api/v2/get_movie_bookmarks.json',
  MOVIE_COMMENTS: 'https://yts.ag/api/v2/movie_comments.json',
  MOVIE_DETAILS: 'https://yts.ag/api/v2/movie_details.json',
  MOVIE_PARENTAL_GUIDES: 'https://yts.ag/api/v2/movie_parental_guides.json',
  MOVIE_REVIEWS: 'https://yts.ag/api/v2/movie_reviews.json',
  MOVIE_SUGGESTIONS: 'https://yts.ag/api/v2/movie_suggestions.json',
  REQUEST_MAKE: 'https://yts.ag/api/v2/make_request.json',
  USER_DETAILS: 'https://yts.ag/api/v2/user_details.json',
  USER_FORGOT_PASSWORD: 'https://yts.ag/api/v2/user_forgot_password.json',
  USER_KEY: 'https://yts.ag/api/v2/user_get_key.json',
  USER_PROFILE: 'https://yts.ag/api/v2/user_profile.json',
  USER_REGISTER: 'https://yts.ag/api/v2/user_register.json',
  USER_RESET_PASSWORD: 'https://yts.ag/api/v2/user_reset_password.json',
  USER_SETTINGS_EDIT: 'https://yts.ag/api/v2/user_edit_settings.json',
};
