module.exports = {
  COMMENT_ADD: '/make_comment.json',
  COMMENT_DELETE: '/delete_comment.json',
  COMMENT_LIKE: '/like_comment.json',
  COMMENT_REPORT: '/report_comment.json',
  LIKE_MOVIE: '/like_movie.json',
  LIST_UPCOMING: '/list_upcoming.json',
  LIST_MOVIES: '/list_movies.json',
  MOVIE_BOOKMARK_ADD: '/add_movie_bookmark.json',
  MOVIE_BOOKMARK_DELETE: '/delete_movie_bookmark.json',
  MOVIE_BOOKMARK_GET: '/get_movie_bookmarks.json',
  MOVIE_COMMENTS: '/movie_comments.json',
  MOVIE_DETAILS: '/movie_details.json',
  MOVIE_PARENTAL_GUIDES: '/movie_parental_guides.json',
  MOVIE_REVIEWS: '/movie_reviews.json',
  MOVIE_SUGGESTIONS: '/movie_suggestions.json',
  REQUEST_MAKE: '/make_request.json',
  USER_DETAILS: '/user_details.json',
  USER_FORGOT_PASSWORD: '/user_forgot_password.json',
  USER_KEY: '/user_get_key.json',
  USER_PROFILE: '/user_profile.json',
  USER_REGISTER: '/user_register.json',
  USER_RESET_PASSWORD: '/user_reset_password.json',
  USER_SETTINGS_EDIT: '/user_edit_settings.json',
};
